name: Latest blog post workflow
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Latest Post
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.trfore.com/posts/index.xml"
          max_post_count: 3
